@startuml

box "Client" #LightGrey
actor "Client" as User
actor Thread1
actor Thread2
participant LindaClient
participant RemoteCallbackImpl
end box
box "Serveur" #LightBlue
actor RMI
participant LindaServer
participant LindaRemote
participant ServerCallback
participant "LindaCentralized" as Linda
end box

group Démarrage du serveur RMI

RMI -> LindaServer: Démarre le serveur

activate LindaServer

LindaServer -> LindaServer: createRegistry(4000)

LindaServer -> LindaRemote: Crée LindaRemoteImpl()

LindaRemote --> LindaServer:

LindaServer -> LindaServer: registry.bind("LindaServer", LindaRemoteImpl);

LindaServer --> RMI: Affiche "// system ready //"

end

User -> User: main()

group Connexion du client

User -> LindaClient : new linda.server("//localhost:4000/");
LindaClient -> LindaClient : LocateRegistry.get(localhost, 4000);
LindaClient -> LindaServer : registry.lookup("LindaServer");
LindaServer --> LindaClient
LindaClient --> User

end

User -> Thread1: start()

group Callback en Take

Thread1 -> Thread1 : motif = new Tuple(Integer.class, String.class)

Thread1 -> LindaClient: eventRegister(TAKE, IMMEDIATE, motif, callbackT1_take)

LindaClient -> RemoteCallbackImpl : C1 = new RemoteCallbackImpl(callbackT1_take);

activate RemoteCallbackImpl

RemoteCallbackImpl --> LindaClient

LindaClient -> LindaRemote : eventRegister(TAKE, IMMEDIATE, motif, C1)

LindaRemote -> ServerCallback : c1 = new ServerCallback(C1)

activate ServerCallback

ServerCallback --> RemoteCallbackImpl : c1 

LindaRemote -> Linda:  eventRegister(TAKE, IMMEDIATE, motif, c1)

Linda --> LindaRemote

LindaRemote --> LindaClient

LindaClient --> Thread1

end

note over Linda : motif \nNOT \nFOUND

Linda -> Linda : templateCallbackTake.put\n(motif, callbackT1_take)

User -> Thread2: start()

group Callback en Take

Thread2 -> Thread2 : motif = new Tuple(Integer.class, String.class)

Thread2 -> LindaClient: eventRegister(TAKE, IMMEDIATE, motif, callbackT2_take)

LindaClient -> RemoteCallbackImpl : C2 = new RemoteCallbackImpl(callbackT2_take);

activate RemoteCallbackImpl

RemoteCallbackImpl --> LindaClient

LindaClient -> LindaRemote : eventRegister(TAKE, IMMEDIATE, motif, C2)

LindaRemote -> ServerCallback : c2 = new ServerCallback(callbackT2_take)

activate ServerCallback

ServerCallback --> LindaRemote

LindaRemote -> Linda : eventRegister(TAKE, IMMEDIATE, motif, c2)

Linda --> LindaRemote

LindaRemote --> LindaClient

LindaClient --> Thread2

end

note over Linda : motif \nNOT \nFOUND

Linda -> Linda : templateCallbackTake.put\n(motif, callbackT2_take)

group Callback en Read

Thread2 -> LindaClient: eventRegister(READ, IMMEDIATE, motif, callbackT2_read)

LindaClient -> RemoteCallbackImpl : C3 = new RemoteCallbackImpl(callbackT2_read);

activate RemoteCallbackImpl

RemoteCallbackImpl --> LindaClient

LindaClient -> LindaRemote: eventRegister(READ, IMMEDIATE, motif, C3)

LindaRemote -> ServerCallback : c3 = new ServerCallback(callbackT2_read)

activate ServerCallback

ServerCallback --> LindaRemote

LindaRemote -> Linda: eventRegister(READ, IMMEDIATE, motif, c3)

Linda --> LindaRemote

LindaRemote --> LindaClient

LindaClient --> Thread2

end

note over Linda : motif \nNOT \nFOUND

Linda -> Linda : templateCallbackRead.put\n(motif, callbackT2_read)

group Write d'un tuple correspondant aux 3 callbacks

Thread2 -> LindaClient: linda.write(new Tuple(4, "foo"))

LindaClient -> LindaRemote: linda.write(new Tuple(4, "foo"))

LindaRemote -> Linda : linda.write(new Tuple(4, "foo")) 

Linda --> LindaRemote

LindaRemote --> LindaClient

LindaClient --> Thread2

end

note over Linda : motif \nFOUND

group Rappels des callbacks

Linda -> ServerCallback : templateCallbackRead.get(callbackT2_read).call(Tuple(4, "foo") 

Linda -> Linda : templateCallbackRead.remove\n(motif, callbackT2_read)

deactivate ServerCallback

ServerCallback -> RemoteCallbackImpl : c3.call(Tuple(4, "foo") 

deactivate RemoteCallbackImpl

RemoteCallbackImpl -> Thread2 : callbackT2_read.call(Tuple(4, "foo")

Linda -> ServerCallback : templateCallbackTake.get(callbackT1_take).call(Tuple(4, "foo")

Linda -> Linda : templateCallbackTake.remove\n(motif, callbackT1_take)

deactivate ServerCallback

ServerCallback -> RemoteCallbackImpl : c1.call(Tuple(4, "foo")

deactivate RemoteCallbackImpl

RemoteCallbackImpl --> Thread1 : callbackT1_take.call(Tuple(4, "foo")

end

Thread1 --> User

note over Thread2 #FFAAAA: callbackT2_take n'est jamais rappelé

note over RemoteCallbackImpl #FFAAAA: Tourne à l'infini\ncar un callback est toujours\nen attente

@enduml
